apiVersion: v1
kind: Namespace
metadata:
  name: redis
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
spec:
  destination:
    namespace: redis
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: redis
    repoURL: https://github.com/lcostea/argocd-helm-deployment.git
    targetRevision: master
    valuesFiles:
    - values.yaml
  syncPolicy:
    automated:
      prune: true
